services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\ScheduledMessengerBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection}'
